// Unit stat definitions
const UNIT_DEFINITIONS = {
    melee1: {
        name: 'Melee T1',
        type: 'melee',
        tier: 1,
        cost: 15,
        hp: 400,
        maxHp: 400,
        damage: 15,
        attackRange: 35,
        attackCooldown: 1000,
        speed: 120
    },
    ranged1: {
        name: 'Ranged T1',
        type: 'ranged',
        tier: 1,
        cost: 15,
        hp: 60,
        maxHp: 60,
        damage: 84,
        attackRange: 120,
        attackCooldown: 1500,
        speed: 105
    },
    caster1: {
        name: 'Caster T1',
        type: 'caster',
        tier: 1,
        cost: 20,
        hp: 50,
        maxHp: 50,
        damage: 70,
        attackRange: 140,
        attackCooldown: 2000,
        speed: 82,
        aoeRadius: 40
    },
    healer1: {
        name: 'Healer T1',
        type: 'healer',
        tier: 1,
        cost: 18,
        hp: 80,
        maxHp: 80,
        damage: 0,
        healAmount: 50,
        maxTargets: 1,
        attackRange: 100,
        attackCooldown: 2500,
        speed: 90,
        aoeRadius: 0
    },
    melee2: {
        name: 'Melee T2',
        type: 'melee',
        tier: 2,
        cost: 30,
        hp: 800,
        maxHp: 800,
        damage: 35,
        attackRange: 40,
        attackCooldown: 900,
        speed: 135
    },
    ranged2: {
        name: 'Ranged T2',
        type: 'ranged',
        tier: 2,
        cost: 40,
        hp: 120,
        maxHp: 120,
        damage: 168,
        attackRange: 150,
        attackCooldown: 1300,
        speed: 120
    },
    caster2: {
        name: 'Caster T2',
        type: 'caster',
        tier: 2,
        cost: 50,
        hp: 100,
        maxHp: 100,
        damage: 120,
        attackRange: 170,
        attackCooldown: 1800,
        speed: 105,
        aoeRadius: 50
    },
    healer2: {
        name: 'Healer T2',
        type: 'healer',
        tier: 2,
        cost: 45,
        hp: 150,
        maxHp: 150,
        damage: 0,
        healAmount: 80,
        maxTargets: 3,
        attackRange: 120,
        attackCooldown: 2200,
        speed: 100,
        aoeRadius: 0
    },
    melee3: {
        name: 'Melee T3',
        type: 'melee',
        tier: 3,
        cost: 80,
        hp: 1600,
        maxHp: 1600,
        damage: 70,
        attackRange: 45,
        attackCooldown: 800,
        speed: 150
    },
    ranged3: {
        name: 'Ranged T3',
        type: 'ranged',
        tier: 3,
        cost: 100,
        hp: 250,
        maxHp: 250,
        damage: 336,
        attackRange: 180,
        attackCooldown: 1100,
        speed: 135
    },
    caster3: {
        name: 'Caster T3',
        type: 'caster',
        tier: 3,
        cost: 120,
        hp: 200,
        maxHp: 200,
        damage: 200,
        attackRange: 200,
        attackCooldown: 1600,
        speed: 120,
        aoeRadius: 60
    },
    healer3: {
        name: 'Healer T3',
        type: 'healer',
        tier: 3,
        cost: 90,
        hp: 300,
        maxHp: 300,
        damage: 0,
        healAmount: 120,
        maxTargets: 6,
        attackRange: 150,
        attackCooldown: 2000,
        speed: 110,
        aoeRadius: 0
    }
};
