// Unit stat definitions
const UNIT_DEFINITIONS = {
    melee1: {
        name: 'Melee T1',
        type: 'melee',
        tier: 1,
        cost: 15,
        hp: 400,
        maxHp: 400,
        damage: 15,
        attackRange: 35,
        attackCooldown: 1000,
        speed: 120
    },
    ranged1: {
        name: 'Ranged T1',
        type: 'ranged',
        tier: 1,
        cost: 15,
        hp: 60,
        maxHp: 60,
        damage: 84,
        attackRange: 120,
        attackCooldown: 1500,
        speed: 105
    },
    caster1: {
        name: 'Caster T1',
        type: 'caster',
        tier: 1,
        cost: 20,
        hp: 50,
        maxHp: 50,
        damage: 70,
        attackRange: 140,
        attackCooldown: 2000,
        speed: 82,
        aoeRadius: 40
    },
    healer1: {
        name: 'Healer T1',
        type: 'healer',
        tier: 1,
        cost: 18,
        hp: 80,
        maxHp: 80,
        damage: 0,
        healAmount: 35,
        maxTargets: 1,
        attackRange: 100,
        attackCooldown: 2500,
        speed: 90,
        aoeRadius: 0
    },
    melee2: {
        name: 'Melee T2',
        type: 'melee',
        tier: 2,
        cost: 30,
        hp: 800,
        maxHp: 800,
        damage: 35,
        attackRange: 40,
        attackCooldown: 900,
        speed: 135
    },
    ranged2: {
        name: 'Ranged T2',
        type: 'ranged',
        tier: 2,
        cost: 40,
        hp: 120,
        maxHp: 120,
        damage: 168,
        attackRange: 150,
        attackCooldown: 1300,
        speed: 120
    },
    caster2: {
        name: 'Caster T2',
        type: 'caster',
        tier: 2,
        cost: 50,
        hp: 100,
        maxHp: 100,
        damage: 120,
        attackRange: 170,
        attackCooldown: 1800,
        speed: 105,
        aoeRadius: 50
    },
    healer2: {
        name: 'Healer T2',
        type: 'healer',
        tier: 2,
        cost: 45,
        hp: 150,
        maxHp: 150,
        damage: 0,
        healAmount: 55,
        maxTargets: 3,
        attackRange: 120,
        attackCooldown: 2200,
        speed: 100,
        aoeRadius: 0
    },
    melee3: {
        name: 'Melee T3',
        type: 'melee',
        tier: 3,
        cost: 80,
        hp: 1600,
        maxHp: 1600,
        damage: 70,
        attackRange: 45,
        attackCooldown: 800,
        speed: 150
    },
    ranged3: {
        name: 'Ranged T3',
        type: 'ranged',
        tier: 3,
        cost: 100,
        hp: 250,
        maxHp: 250,
        damage: 336,
        attackRange: 180,
        attackCooldown: 1100,
        speed: 135
    },
    caster3: {
        name: 'Caster T3',
        type: 'caster',
        tier: 3,
        cost: 120,
        hp: 200,
        maxHp: 200,
        damage: 200,
        attackRange: 200,
        attackCooldown: 1600,
        speed: 120,
        aoeRadius: 60
    },
    healer3: {
        name: 'Healer T3',
        type: 'healer',
        tier: 3,
        cost: 90,
        hp: 300,
        maxHp: 300,
        damage: 0,
        healAmount: 85,
        maxTargets: 6,
        attackRange: 150,
        attackCooldown: 2000,
        speed: 110,
        aoeRadius: 0
    },
    // Tier 4 - Small exponential growth (~1.6x)
    melee4: {
        name: 'Melee T4',
        type: 'melee',
        tier: 4,
        cost: 150,
        hp: 2600,
        maxHp: 2600,
        damage: 115,
        attackRange: 50,
        attackCooldown: 750,
        speed: 165
    },
    ranged4: {
        name: 'Ranged T4',
        type: 'ranged',
        tier: 4,
        cost: 180,
        hp: 420,
        maxHp: 420,
        damage: 540,
        attackRange: 200,
        attackCooldown: 1000,
        speed: 150
    },
    caster4: {
        name: 'Caster T4',
        type: 'caster',
        tier: 4,
        cost: 210,
        hp: 340,
        maxHp: 340,
        damage: 330,
        attackRange: 220,
        attackCooldown: 1500,
        speed: 135,
        aoeRadius: 70
    },
    healer4: {
        name: 'Healer T4',
        type: 'healer',
        tier: 4,
        cost: 160,
        hp: 500,
        maxHp: 500,
        damage: 0,
        healAmount: 140,
        maxTargets: 8,
        attackRange: 170,
        attackCooldown: 1900,
        speed: 125,
        aoeRadius: 0
    },
    // Tier 5 - Small exponential growth (~1.6x)
    melee5: {
        name: 'Melee T5',
        type: 'melee',
        tier: 5,
        cost: 280,
        hp: 4200,
        maxHp: 4200,
        damage: 185,
        attackRange: 55,
        attackCooldown: 700,
        speed: 180
    },
    ranged5: {
        name: 'Ranged T5',
        type: 'ranged',
        tier: 5,
        cost: 320,
        hp: 700,
        maxHp: 700,
        damage: 870,
        attackRange: 220,
        attackCooldown: 950,
        speed: 165
    },
    caster5: {
        name: 'Caster T5',
        type: 'caster',
        tier: 5,
        cost: 370,
        hp: 560,
        maxHp: 560,
        damage: 530,
        attackRange: 240,
        attackCooldown: 1400,
        speed: 150,
        aoeRadius: 80
    },
    healer5: {
        name: 'Healer T5',
        type: 'healer',
        tier: 5,
        cost: 290,
        hp: 820,
        maxHp: 820,
        damage: 0,
        healAmount: 230,
        maxTargets: 10,
        attackRange: 190,
        attackCooldown: 1800,
        speed: 140,
        aoeRadius: 0
    },
    // Tier 6 - Small exponential growth (~1.6x)
    melee6: {
        name: 'Melee T6',
        type: 'melee',
        tier: 6,
        cost: 500,
        hp: 6800,
        maxHp: 6800,
        damage: 300,
        attackRange: 60,
        attackCooldown: 650,
        speed: 195
    },
    ranged6: {
        name: 'Ranged T6',
        type: 'ranged',
        tier: 6,
        cost: 560,
        hp: 1150,
        maxHp: 1150,
        damage: 1400,
        attackRange: 240,
        attackCooldown: 900,
        speed: 180
    },
    caster6: {
        name: 'Caster T6',
        type: 'caster',
        tier: 6,
        cost: 640,
        hp: 920,
        maxHp: 920,
        damage: 850,
        attackRange: 260,
        attackCooldown: 1300,
        speed: 165,
        aoeRadius: 90
    },
    healer6: {
        name: 'Healer T6',
        type: 'healer',
        tier: 6,
        cost: 520,
        hp: 1350,
        maxHp: 1350,
        damage: 0,
        healAmount: 380,
        maxTargets: 12,
        attackRange: 210,
        attackCooldown: 1700,
        speed: 155,
        aoeRadius: 0
    },
    // Tier 7 - Small exponential growth (~1.6x)
    melee7: {
        name: 'Melee T7',
        type: 'melee',
        tier: 7,
        cost: 900,
        hp: 11000,
        maxHp: 11000,
        damage: 480,
        attackRange: 65,
        attackCooldown: 600,
        speed: 210
    },
    ranged7: {
        name: 'Ranged T7',
        type: 'ranged',
        tier: 7,
        cost: 1000,
        hp: 1900,
        maxHp: 1900,
        damage: 2250,
        attackRange: 260,
        attackCooldown: 850,
        speed: 195
    },
    caster7: {
        name: 'Caster T7',
        type: 'caster',
        tier: 7,
        cost: 1100,
        hp: 1500,
        maxHp: 1500,
        damage: 1360,
        attackRange: 280,
        attackCooldown: 1200,
        speed: 180,
        aoeRadius: 100
    },
    healer7: {
        name: 'Healer T7',
        type: 'healer',
        tier: 7,
        cost: 950,
        hp: 2200,
        maxHp: 2200,
        damage: 0,
        healAmount: 610,
        maxTargets: 15,
        attackRange: 230,
        attackCooldown: 1600,
        speed: 170,
        aoeRadius: 0
    }
};
